### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Petros9** [Petros9/Python-project#1]
- [x] brak kolizji podczas kucania //Kamil
- [x] poruszanie się gorgoli
- [x] animacja chodzenia bohatera 
- [x] animacja chodzenia gorgola
- [x] model skoku
- [x] model hamowania
- [x] boss:
  - [x] skakanie
  - [x] strzelanie
- [x] klasyfikacja platform//Kamil
- [x] wybuchajace mosty //Kamil
- [x] koniec gry

**Comment by Petros9** [comment]
- [ ] flagi jako zakończenia leveli
- [ ] zrobić level wstępny (wprowadzenie w fabułę), dwa do pochodzenia i jeden z bossem

**Comment by Petros9** [comment]
# Pododawać dźwięki:
- [ ] strzał wroga/wieżyczki
- [ ] dźwięk otrzymania obrażeń
- [ ] dźwięk zakończenia levelu
- [ ] dźwięk wybuchu mostu
- [ ] nagrać początkowy dialog

**Comment by Kamilbur** [comment]
# Bugi przy strzelaniu

1. [x] Niepoprawne miejsce wystrzeliwania pocisków
 * Strzały w prawo są jak najbardziej poprawne
![Shoot_right](https://user-images.githubusercontent.com/29152441/82270885-87196300-9976-11ea-9e77-95f13b417c98.png)
* Pociski wychodzące przy strzałach w lewo są przesunięte o jeden CELL_SIZE w lewo od bohatera
![left_shoot](https://user-images.githubusercontent.com/29152441/82271019-e8d9cd00-9976-11ea-874c-8078f37a9687.png)
2. [x] Co bardzo dziwne pociski po opuszczeniu ekranu mają tendencję do powracania - trzeba będzie to naprawić. Mam tu na myśli to, że po wystrzeleniu salwy pocisków w lewo i odczekaniu odpowiednio długo powracają one z prawej strony. Proponowane rozwiązanie to usuwanie kul, gdy tylko opuszczą ekran.

**Comment by Kamilbur** [comment]
- [x] Zrobić z settingsów, animacji itp. dataclasses.
[https://docs.python.org/3/library/dataclasses.html](url)
Wydaje mi się, że będzie działać jak tak samo, a będzie fajnie - choć troszkę przepisywania, ale nie powinno być źle.
To chyba z pythona 3.7, więc takie prawie nowe featuresy XD.
